#!/bin/bash

# FIXME: when is eth0 internet and when is it local? That should be discovered. How? I don't know
docker exec --privileged $1 iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
docker exec --privileged $1 iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT
docker exec --privileged $1 iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
